### ISSUE TITLE
An error appears when entering the site "Check BETA for more features => heightmap.skydark.pl/beta"

### ISSUE THREAD

**Issue by Sayder0690** [sysoppl/Cities-Skylines-heightmap-generator#100]
An error appears when entering the site "Check BETA for more features => heightmap.skydark.pl/beta"
The interface is working but the map does not show a white screen.
If I click on “Ok”, nothing happens, if I follow the link that the site recommends to me, then the same thing happens, nothing happens.
![Снимок](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/171448068/1e77bcdf-3e22-4bcd-a4c1-bb7bb2b85bd1)

**Comment by 935873855** [comment]
An error appears when entering the site "Check BETA for more features => heightmap.skydark.pl/beta"

**Comment by sysoppl** [comment]
Thats not an error, thats info box guys... There is beta version with more features
When there is no map api token just expired and you need to wait few days
