### ISSUE TITLE
An error appears when entering the site "Check BETA for more features => heightmap.skydark.pl/beta"

### ISSUE THREAD

**Issue by 935873855** [sysoppl/Cities-Skylines-heightmap-generator#101]
An error appears when entering the site "Check BETA for more features => heightmap.skydark.pl/beta"
![17](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/132875400/1a4169f3-f74a-476c-a007-149f0ac4a716)

**Comment by luzhou1573** [comment]
2024.6.5This question remains, is it possible that the author has abandoned the project?

**Comment by sysoppl** [comment]
Thats not an error, thats info there is beta version with more features
