### ISSUE TITLE
Not able to load or downloard when I change the map scale

### ISSUE THREAD

**Issue by Caioshindo** [sysoppl/Cities-Skylines-heightmap-generator#102]
As the title says. If I want anything smaller than 17 km, the program does not load:

![image](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/174222549/908c226f-52ee-43f5-adff-d4d9d6562cb6)

**Comment by sysoppl** [comment]
I don't touch original author code. He set 17 as minimum so it probably wont work with smaller values. Maybe you can just crop the 17x17 one to match smaller?
