### ISSUE TITLE
White Screen, Expired Token(?)

### ISSUE THREAD

**Issue by MurphysLa-w** [sysoppl/Cities-Skylines-heightmap-generator#104]
As of 3. Jul the website has no functionality
Regarding past issues the Token has probably expired

**Comment by robert-corlett** [comment]
sign up for a free mapbox account, get yourself a token
then build the app yourself with the correct token

or for the lazy, open the demo website, open dev tools, edit app.js under 'sources', find the mapboxgl.accessToken rotating entries and edit them. then right click the app.js title tab and save an a local override
