### ISSUE TITLE
Bypass the most common issue: Install this code locally and input your own API credentials. 

### ISSUE THREAD

**Issue by sixeyeco** [sysoppl/Cities-Skylines-heightmap-generator#105]
[See below]

**Comment by sixeyeco** [comment]
I followed the instructions below and had a working version being run on my machine. That was, until the lates issue (https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/110).

Assuming the Generator code will work again soon, here's the steps I took to install it locally:
https://pinter.org/archives/15848

**Comment by sysoppl** [comment]
fixed:
- now you need to put own mapbox api token to make this app work
- replaced fa icons with tabler icons
- bumped some libs

I tested this quickly and looks like everything is working and I'm able to download maps. If any issues occur please open new issue.
