### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Mezame-ux** [sysoppl/Cities-Skylines-heightmap-generator#110]
When I open the website, it looks like this and I can't use it. because there is no UI.
[Screenshot 2024-09-16 09 21 09](https://github.com/user-attachments/assets/20d23b38-e5c9-40e6-8c18-adda409cd1bf)

**Comment by sixeyeco** [comment]
Me too! I thought it was the Mapbox limit. I installed XAMPP/Apache, copied this code on my machine and created a Mapbox account.  I get the same thing.

**Comment by sixeyeco** [comment]
Debugger indicates an issue with FontAwesome token. Could this be the issue?

**Comment by LongJackrules** [comment]
I'm also having this issue, exactly as stated by @Mezame-ux .

**Comment by AScarselli** [comment]
Same Issue as  @Mezame-ux. No UI

**Comment by sysoppl** [comment]
Im working on fix two most common issues

**Comment by sysoppl** [comment]
fixed:
- now you need to put own mapbox api token to make this app work
- replaced fa icons with tabler icons
- bumped some libs

I tested this quickly and looks like everything is working and I'm able to download maps. If any issues occur please open new issue.
