### ISSUE TITLE
Add option to export raw map image (no grid, no 5x5 highlight) for use as an overlay

### ISSUE THREAD

**Issue by punknubbins** [sysoppl/Cities-Skylines-heightmap-generator#13]
Subject is pretty self explanatory. For those of us trying to build out simulations/scenarios of our home towns, the height map output is perfect, but a clean copy of an identical sized map image without the grid and highlighting, to use as an overlay, would make it super easy to lay out roads in the editor.

**Comment by measiala** [comment]
As an intermediate goal, could you add the bounding box dimensions to the Info.txt?  I previously used Maperitive along with terrain.party with great success just having the bounding box. It seems that you may already have it in the code or else there is an API call to grab it from Mapbox.
