### ISSUE TITLE
Map not working/server problem??

### ISSUE THREAD

**Issue by Tobi15236** [sysoppl/Cities-Skylines-heightmap-generator#16]
When you start up the map generator, you only see a blank screen instead of the map. When trying to search for a city (using the 
[ i ] Button it reads "there was a problem reaching the server". At the moment, there is no chance of getting a highmap because of this isssue. 
Edit: using Google Chrome instead of Firefox did not make a difference

**Comment by wallofchaos** [comment]
sad sad. I need a Height map done.

**Comment by 20210904** [comment]
Can also confirm I am having this issue and tried several different browsers, no luck.

**Comment by sysoppl** [comment]
Whops token expired. Also github is not notifing me about new issues, so sorry for the delay...

**Comment by sysoppl** [comment]
@Tobi15236 @wallofchaos @20210904 this is fixed now. Sorry for the delay

**Comment by Tobi15236** [comment]
Thx for fixing the issue.

Information for everyone, who still had problems AFTER the fix: you have to DELETE the cookies for the website in order for the map to load normally again.
