### ISSUE TITLE
Css file not updated

### ISSUE THREAD

**Issue by nonta1234** [sysoppl/Cities-Skylines-heightmap-generator#19]
The file of "https://cs.heightmap.skydark.pl/styles.css" has not been updated, so the layout of the information panel is off.

**Comment by sysoppl** [comment]
![image](https://user-images.githubusercontent.com/30871217/132292644-61651922-66af-4d1f-b981-1850fd7c7209.png)
It looks OK for me. Can you share screenshot or did you delete cache / cookies for this website?

**Comment by nonta1234** [comment]
It improved when I deleted the cookie.

thanks
