### ISSUE TITLE
in height map i see "tile lines" i cant fix it.

### ISSUE THREAD

**Issue by RevOfficial1** [sysoppl/Cities-Skylines-heightmap-generator#2]
Im map creator and i very need to have terrain party or alternative. i have problems
![heightmap (4)](https://user-images.githubusercontent.com/83837391/117500599-831a9280-af85-11eb-97a1-4d651c1f4a6d.png)
 Lines in heightmaps. please help me! i very need remove it

**Comment by sysoppl** [comment]
Hey, sorry for long response time, but github didn't send me any notification about new issues here.
I will look into this soon (probably next week), due to no time right now. Should be easy fix

For now, if you want you can use RAW files.

**Comment by clentl** [comment]
I had the same Issue with the lines, I didn't see a way to import the .raw file. I also saw another post talking about shallow water ways, I have having that issue too. I have one other question, I was wanting to use the overlay mod to put the image over it in map editor, but you need to lat and long of all four corners. Is there a way to get that info from your map? You get the overlay map from openstreetmap Thank you for all your work

**Comment by sysoppl** [comment]
Hey, lines in png will be fixed this weekend, we have PR for this. I also have free time from now, so I will create more options for RAW/PNG and grid in the menu ASAP. Thank you for your patience

**Comment by sysoppl** [comment]
Merged. Website was updated. Please check readme to see how to use it.
