### ISSUE TITLE
Vector Tiles | MapBox exceed API requests - self host instead

### ISSUE THREAD

**Issue by sysoppl** [sysoppl/Cities-Skylines-heightmap-generator#21]
We are using free tier of MapBox API, and it has limits which now exceeds. 

**PLEASE REFRESH WEBSITE IF IT SHOWS NO MAP!**

**Comment by sysoppl** [comment]
MapBox is now charging me for API requests which is not good
![image](https://user-images.githubusercontent.com/30871217/133974907-69ead75a-db89-4465-818a-b2c4959b3125.png)

**Comment by sysoppl** [comment]
For now I will continue to host this service

**Comment by nonta1234** [comment]
I'm not sure if it's good, but I suggest using multiple people's tokens.

**Comment by nonta1234** [comment]
Hi sysoppl
I'm trying to avoid making requests to the API by caching the downloaded Vector Tiles and loading it from the cache next time.

**Comment by sysoppl** [comment]
Hey, thank you for your effort!

**Comment by sysoppl** [comment]
![image](https://user-images.githubusercontent.com/30871217/137100914-661a2d08-5af9-4101-9602-ec3ccc31b894.png)
![image](https://user-images.githubusercontent.com/30871217/137100955-54f762a4-ce7f-4e4a-b802-7db72b6ae72f.png)


This is very big issue right now. I might close this project due to too much api requests it is generating now. Waiting for any feedback from you guys

**Comment by nonta1234** [comment]
Hi
The fact that many requests despite the built-in cache control means that users are often downloading new regions. After all, I think that it is necessary to create a mirror site with another access token or replace the access token regularly.

**Comment by nonta1234** [comment]
Oh...that's true.
Would you like to stop using vector tiles and consider using OSM?

**Comment by nonta1234** [comment]
Vector Tiles are only used to extract the water area, so you don't currently need files for all layers.

http://hydro.iis.u-tokyo.ac.jp/~yamadai/OSM_water/v2.0_2021Feb/OSM_WaterLayer.pbf

Because the size is too large as it is, if you can tiling the data on the above sites, you can manage it in a smaller size. I don't know the difference between OSM data and Mapbox Vector Tile specifications, but I can load it as long as I have tiles.

**Comment by 123ysys** [comment]
Seems that the API cost is a huge problem to site owner. I just registered my mapbox account and is going to self-hosting. How can I replica your website on my windows 10?

**Comment by sixeyeco** [comment]
Instructions to host it yourself: https://pinter.org/archives/15848 

It worked for quite a while until.... https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/110

But, by the time "you" read this the Map code here might be working again.

**Comment by sysoppl** [comment]
fixed:
- now you need to put own mapbox api token to make this app work
- replaced fa icons with tabler icons
- bumped some libs

I tested this quickly and looks like everything is working and I'm able to download maps. If any issues occur please open new issue.

**Comment by sixeyeco** [comment]
Well done. So much easier to use your link and our token. Thank you very much!
