### ISSUE TITLE
[Notification] Map size

### ISSUE THREAD

**Issue by Dushess** [sysoppl/Cities-Skylines-heightmap-generator#3]
We have 17.28 max length, and roads actually big enough from first look. So grid of 17.2x17.2 should be here. 
If you not mentioning common view which is rougtly considered as 18.

**Comment by sysoppl** [comment]
Sorry but I really don't understand. Are you saying, that this generator is generating 17.28 km border, so it should generate 17.2 instead?

**Comment by RevOfficial1** [comment]
sysoppl, can you create map size tool? i wanna create map 8х8km or other size, if you can create it, i'll be happy

**Comment by Orijuke** [comment]
Hi! I'm glad I've found your generator, but I noticed that it makes map 10*10, not 18*18. Or I do smth wrong?
![map_site](https://user-images.githubusercontent.com/57594615/117993980-a2d10280-b359-11eb-91aa-0fba5108fc6c.jpg) 
![heightmap](https://user-images.githubusercontent.com/57594615/117994129-bc724a00-b359-11eb-9334-f6f92ed39d7e.png)
![map_game](https://user-images.githubusercontent.com/57594615/117994044-ad8b9780-b359-11eb-8e8c-1dbc76b34b78.jpg)
![real_map](https://user-images.githubusercontent.com/57594615/117994183-c8f6a280-b359-11eb-9521-8ad6802c1523.jpg)

**Comment by sysoppl** [comment]
@RevOfficial1 Please create new issue with your request, will be easier for me to organise

@Orijuke  It seems that you're using PNG. Can you try RAW if it will be the same?

**Comment by Orijuke** [comment]
I used RAW when creating the map, I just wanted to check what the image looks like, so I downloaded PNG later

**Comment by iiSover** [comment]
@sysoppl  Hi, I noticed the same problem as @Orijuke.

By looking at https://skylines.paradoxwikis.com/Heightmap it is said that the heightmap has a resolution of 16.65m per pixel. But in your code it seems that you're using a resolution of 12m/px with the zoom var in app.js / getHeightmap() / line ~344.

Would it be possible to change that var without breaking the code to get the 16.65m/px scale ?

**Comment by sysoppl** [comment]
@iiSover  Hey, I will look into this in few days! Thanks for sharing, as I really don't have time to play CS now to test it.

**Comment by iiSover** [comment]
@sysoppl Here's some complementary screenshots showing that it results in the .raw beeing 2 tiles shorter than the grid.

![image](https://user-images.githubusercontent.com/84223825/118363521-0f841100-b595-11eb-8cae-5e22666ce18a.png)

![image](https://user-images.githubusercontent.com/84223825/118363527-1874e280-b595-11eb-9d1b-9dffde53c4a1.png)

**Comment by sysoppl** [comment]
So, after trying to fix this I assume, that there is no perfect value for zoom / resolution for this and it all depends on the place you select. If the image is perfectly aligned at the equator, it will be magnified in the north on same settings (as shown below). For now I don't have any solution for this, but I'm thinking 
![obraz](https://user-images.githubusercontent.com/30871217/123507599-a949de00-d66a-11eb-9d78-88ee6bed48fe.png)
![obraz](https://user-images.githubusercontent.com/30871217/123507709-3c831380-d66b-11eb-91ca-040cc6a03bb5.png)

**Comment by Groegi83** [comment]
Dear sysoppl,

just to clarify your results - grid on the map an exported heightmap only fit around the equatorial? Anywhere else the heightmap will be bigger? I encountered the same behaviour as mentioned in map siz issue #9 when trying to generate a heightmap for Sao Paulo - the heightmap covers a bigger area than the grid.

**Comment by sysoppl** [comment]
> Dear sysoppl,
> 
> just to clarify your results - grid on the map an exported heightmap only fit around the equatorial? Anywhere else the heightmap will be bigger? I encountered the same behaviour as mentioned in map siz issue #9 when trying to generate a heightmap for Sao Paulo - the heightmap covers a bigger area than the grid.

It was fitting  with specific zoom and resolution values (which are not available in main branch). I was testing how to fit map everywhere on earth and this was my results. I didn't test it with default settings/main branch, so I'm not sure how it works with actual settings. There is no fix at the moment. 
I'm testing custom zoom values, where users can enter value to fit map to their needs. No ETA at the moment

**Comment by Dushess** [comment]
I'm back. mentioned that base lenght in game is 17.28, but we actually have bigger issue as i can see. Gonna chech also now.

**Comment by Dushess** [comment]
I'm back. Mentioned that base lenght in the game is 17.28, but we actually have bigger issue as I can see. Gonna check later, but what method do you use? And I've not found initially anything about output format in the interface.

**Comment by nonta1234** [comment]
@sysoppl Hi! I tried to solve the issue of map size and position. I modified "app.js". I think it's probably working fine.

**Comment by sysoppl** [comment]
Hey @nonta1234, I saw your code, but it is like 'remove all lines of code (-640), and add them with changes (+710)', so I'm unable to find changes you made. If you can edit/remove/add just the lines that are necessary, then send PR, so I can test and merge it would be great!
![image](https://user-images.githubusercontent.com/30871217/127503195-9cc2fc0f-d069-4285-92c8-34113535e4de.png)

**Comment by nonta1234** [comment]
Thanks for checking.
I had failed to create the commit, so I recreated the commit.
I'll send PR in a few days.

**Comment by nonta1234** [comment]
Dear sysoppl,

Thanks for checking.
I had failed to create the commit, so I recreated the commit.
I'll send PR in a few days.
