### ISSUE TITLE
I can't export small areas heightmap

### ISSUE THREAD

**Issue by Marotovski** [sysoppl/Cities-Skylines-heightmap-generator#30]
I was trying to save a 5km x 5km area, but the actual cap is 17,28km. I'm think that is probably a limitation (because probably height data don't have to much resolution) but even a slow res map output will help a lot. There is a lot of work exporting the minimum height map size and trying to lineup the match 5km x 5km match from the satelite.
Don't know if this is possible, but a export what use the height contours (grayscale blocks representing each height contours zone) for lower resolution would be nice too.

**Comment by sysoppl** [comment]
Exporting 5x5 is too small as you said - it will be just one big blurred spot.
