### ISSUE TITLE
Arctic Tiles is really bad quality

### ISSUE THREAD

**Issue by DarwinDOS** [sysoppl/Cities-Skylines-heightmap-generator#37]
I don't know, can you fix this, or no, but in Arctic satelite images is really low quality.

**Comment by sysoppl** [comment]
That's probably due to https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/21

**Comment by sysoppl** [comment]
Nope, thats not this generator problem. Just data from our heightmap provider - mapbox is bad quality there. I cannot do anything about it.
