### ISSUE TITLE
downloaded image is white (blank) how do i fix this?

### ISSUE THREAD

**Issue by andrgamer3** [sysoppl/Cities-Skylines-heightmap-generator#39]

**Comment by sysoppl** [comment]
Due to https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/21
If you want to self host, generate new API from MapBox and put it here: https://github.com/sysoppl/Cities-Skylines-heightmap-generator/blob/278cd4345fee9b496bef2b4998e8d228c239bce6/src/app.js#L47

**Comment by shawnjbragdon-0** [comment]
This doesn't solve the issue.

**Comment by sysoppl** [comment]
Well, I cannot reproduce it. What are you downloading? PNG, RAW, ZIP?

**Comment by Peregrine05** [comment]
You need to set the Base level to a value that is within or near the height range of of the selected area, but not above the area.
If the base level is too low, then all the terrain in the map will be above the maximum height range of the heightmap file, making it be colored completely white. If the base level is set above the maximum height of the terrain in the map, then the heightmap file will be completely black, as none of the terrain is within the heightmap range.
![Heightmap](https://user-images.githubusercontent.com/92183530/156357721-43d53d82-cf22-463c-8dee-bc3747579bc5.png)

**Comment by TheBango** [comment]
I used the calculator buttons to set the base level and the height scale, so I guess everything should be set up correctly, but I still get a black image when I try to download a PNG of the heightmap.

![image](https://user-images.githubusercontent.com/37959818/202904287-176fc723-c2c1-4b94-9573-965410ca029d.png)

Is the heightmap generator no longer maintained?
