### ISSUE TITLE
Rivers not comming through enough

### ISSUE THREAD

**Issue by AlexGamesMore** [sysoppl/Cities-Skylines-heightmap-generator#4]
Hey

I've been trying out your height maps and they look to be working fine. But most bodies of water have issues with not being pronounced enough. It will draw the rivers very lightly in CS making it impossible to add water into the map without flooding the entire map. Is it possible to add the contour layer for water to the export and tell it to drop that down like 5 extra meters?

Thanks
Alex

**Comment by sysoppl** [comment]
Fixed in https://github.com/sysoppl/Cities-Skylines-heightmap-generator/pull/17
