### ISSUE TITLE
OSM export error 

### ISSUE THREAD

**Issue by Shinzef** [sysoppl/Cities-Skylines-heightmap-generator#42]
I have been trying to export osm but it gives this error when opening the osm file:

<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.57 93a4d346">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2022-02-05T14:46:53Z"/>

  <bounds minlat="33.7756606" minlon="-118.4279359" maxlat="34.1353873" maxlon="-117.9942487"/>

<remark> runtime error: Query ran out of memory in "recurse" at line 1. It would need at least 630 MB of RAM to continue. </remark>

</osm>

**Comment by Shinzef** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.57 93a4d346">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2022-02-05T14:46:53Z"/>

  <bounds minlat="33.7756606" minlon="-118.4279359" maxlat="34.1353873" maxlon="-117.9942487"/>

<remark> runtime error: Query ran out of memory in "recurse" at line 1. It would need at least 630 MB of RAM to continue. </remark>

</osm>

**Comment by sysoppl** [comment]
Well, that is probably not a problem with this generator. Until it generate file and you can download it it works as intended. If you have any problems with opening files you should ask author of these programs.

**Comment by Shinzef** [comment]
It's a problem with the generator, and I'm simply using notepad to view .osm files as they are simply XML. This happens when the server used to generate the osm file has not had enough ram to generate these nodes, and it would simply spit out a 1kb .osm useless file. In some areas that have fewer nodes, it works. I used this tool in the LA area, which has prob many nodes.

**Comment by sysoppl** [comment]
Well, this is hosted on dedicated server with Xeon and a lot of DDR4 soooo I will check php configs when I will be able to.

**Comment by Shinzef** [comment]
As far as I know, there's a config file that limits the memory that can be
used. But thanks!
