### ISSUE TITLE
Europe map

### ISSUE THREAD

**Issue by ZanispleveLV** [sysoppl/Cities-Skylines-heightmap-generator#43]
Hi!

I can take any information about map in Europe, example: Berlin, Viluns or Warsawa. Maybe you can help me with that?

**Comment by sysoppl** [comment]
Hey
What do you mean by that? This is a heightmap generator, it outputs image and coordinates

**Comment by ZanispleveLV** [comment]
I mean, i tried take Vilnius map and it won't download any height map file, but i know there is terrain. So i can't make realistic city terrain what i want

**Comment by ZanispleveLV** [comment]
> Hey What do you mean by that? This is a heightmap generator, it outputs image and coordinates

I mean, i tried take Vilnius map and it won't download any height map file, but i know there is terrain. So i can't make realistic city terrain what i want
