### ISSUE TITLE
[Feature request] - Extract CSV map file

### ISSUE THREAD

**Issue by VitalBrain** [sysoppl/Cities-Skylines-heightmap-generator#44]
Could it be possible to extract data into txt or csv file ?
like | long. | lat. | elevation |

**Comment by sysoppl** [comment]
txt file is generated when you download zip file, check it out

**Comment by VitalBrain** [comment]
Yes I saw it but only metadata are stored there, I suggest to add full elevation data associated with coordinates

**Comment by sysoppl** [comment]
I'm not developing this software anymore, just hosting it. I will however merge any pull requests, so please create one if you can.
Thanks
