### ISSUE TITLE
[RFE] - Include rail networks on "Change map style > Map style: > Streets"

### ISSUE THREAD

**Issue by Jason-Maynard** [sysoppl/Cities-Skylines-heightmap-generator#46]
Is it possible from a cost and complexity standpoint to enhance the "Streets" Map Style to include rail networks please?

Rail networks are a major component in Cities Skylines and it would be ideal to see them included in the downloadable Map Style.

Thanks for this wonderful tool!

**Comment by lunar54** [comment]
Would also like to see Map Style to include rail networks and able to remove labels. on the Streets Map Style rail network is there but the exported image does not contain it.

**Comment by sysoppl** [comment]
I'm not developing this software anymore, just hosting it. I will however merge any pull requests, so please create one if you can.
Thanks
