### ISSUE TITLE
[Request] Set custom resolution for the map export

### ISSUE THREAD

**Issue by Jimmarn** [sysoppl/Cities-Skylines-heightmap-generator#48]
It would be very nice to be able to export the map overlay in higher resolution as mentioned earlier, I've noticed it exported as 2k now, but it would have been great to be able to specify a custom resolution in a 1:1 ratio in the settings tab. 
Very useful for using things like overlay image when doing roads in the editor. 

Likewise even though Cities skylines only accepts 1081 resolution heightmap, it would have been great to be able to set a custom resolution for the heightmap as well in case you want some more detail when working in programs like world machine customizing the map. Latter isn't really necessary though, since the game doesn't utilize higher resolution, just a nice to have.

**Comment by sysoppl** [comment]
I'm not developing this software anymore, just hosting it. I will however merge any pull requests, so please create one if you can.
Thanks
