### ISSUE TITLE
How to open .raw files?

### ISSUE THREAD

**Issue by rmfurm** [sysoppl/Cities-Skylines-heightmap-generator#5]
Hey, ive tried opening the .raw file in both the photos app and paint.net. 
![image](https://user-images.githubusercontent.com/86154178/122642203-90ae6500-d14c-11eb-8997-a0c8b6a05b20.png)
![image](https://user-images.githubusercontent.com/86154178/122642219-a02dae00-d14c-11eb-819f-d9785614999a.png)

Ive also tried converting to .png, but nothing works.

![image](https://user-images.githubusercontent.com/86154178/122642254-c81d1180-d14c-11eb-827a-7ceade98509e.png)

Any help would be appreciated

**Comment by sysoppl** [comment]
You can open it with photoshop. I didn't tried any other software

**Comment by rmfurm** [comment]
yeah just got photoshop and it works 👍
