### ISSUE TITLE
small region to the right is deeper

### ISSUE THREAD

**Issue by Ghotrix** [sysoppl/Cities-Skylines-heightmap-generator#51]
The resulting PNG contains a small rectangle that is darker (deeper) in comparison to the whole exported area.

![heightmap](https://user-images.githubusercontent.com/284072/159745047-a878cff4-e728-494b-891d-d48a8a9ca3ff.png)

**Comment by Cariyla** [comment]
Same issue here, happens on any region and any browser I've tried (FF, Chrome, old IE, Edge).

**Comment by sysoppl** [comment]
Hey. I reverted version on main page to older, more stable. Please try it now, but remember to remove cookies and cache. Newer features are on beta page ( https://heightmap.skydark.pl/beta )
