### ISSUE TITLE
[Feature Request] Optional Grid Layout

### ISSUE THREAD

**Issue by TheBango** [sysoppl/Cities-Skylines-heightmap-generator#57]
I don't know if it's possible, but I would like to see a system where we can switch between the current Cities:Skylines grid layout and a free grid layout.

![HeightmapSkydark_OneTileSelection](https://user-images.githubusercontent.com/37959818/171266079-f4f7061b-71d1-4b3b-991b-a1d09a4e1b78.png)

With the free grid layout, we would then have the possibility to determine the size of the grid as well as the size of the tiles (smaller size equals higher resolution). Then we should be able to download the maps (height map, street map, satellite map, osm file) for each selected tile (either one tile or multiple tiles). The reason for this idea is that I think that we not only should achieve a higher resolution per tile than it is currently the case but you can also promote this generator to generate detailed real world maps for other games or applications.

![HeightmapSkydark_MultipleTileSelection](https://user-images.githubusercontent.com/37959818/171269149-349433ff-b0e4-49ac-bdd0-7ad9d8aac444.png)

If multiple tiles are selected then e.g. the heightmaps of all tiles should be downloadable in a zip file and be numbered according to the naming of UDIMs from bottom left to top right (e.g. madrid_hm_1001 - madrid_hm_1045). Those maps can then be merged by the user to one PNG in an image editing program like Photoshop to not only get a greater but more detailed heightmap.

![image](https://user-images.githubusercontent.com/37959818/171268987-5e88ba21-f889-4905-aaa5-0018be896906.png)

I hope I have expressed my idea understandably and would appreciate it being implemented.

**Comment by sysoppl** [comment]
I'm not developing this software anymore, just hosting it. I will however merge any pull requests, so please create one if you can.
Thanks

**Comment by TheBango** [comment]
Hi Patryk,

I'm sorry to hear that you've stopped developing on the heightmap
generator. May I ask you why?

Cheers,
David

**Comment by sysoppl** [comment]
Please see https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/73

**Comment by TheBango** [comment]
Thank you for replying!

Okay, I've seen this announcement afterwards and also that you're leftover with a big charge for providing us with this great tool. Were you able to settle the debts or do you still have to pay for it?

Also, if you don't mind, I would like to chat with you in a more private way. Is there any chance?

**Comment by sysoppl** [comment]
Feel free to contact me on discord (sysop#5365)

**Comment by TheBango** [comment]
Thanks, I will.

Patryk ***@***.***> schrieb am Do., 8. Dez. 2022, 19:12:

**Comment by TheBango** [comment]
@sysoppl 
Hey, I've sent you a request on Discord

**Comment by sysoppl** [comment]
I've accepted it
