### ISSUE TITLE
River isn't fully recognized 

### ISSUE THREAD

**Issue by Phovey** [sysoppl/Cities-Skylines-heightmap-generator#58]
I'm trying to make a city and a lot of the river isn't getting picked up by the heatmaps.
![Screenshot 2022-05-31 221920](https://user-images.githubusercontent.com/106639936/171314891-562ce8a5-60f8-401b-ac08-a5fdfe00bbdd.png)

**Comment by TheBango** [comment]
I think this is an issue due to Open Street Map (OSM) as the heightmap generator uses the data from there. In this case OSM needs to be improved so that we get a better result in the heightmap generator.

**Comment by sysoppl** [comment]
I'm not developing this software anymore, just hosting it. I will however merge any pull requests, so please create one if you can.
Thanks
