### ISSUE TITLE
Export from .raw to png in Photoshop not working. 

### ISSUE THREAD

**Issue by rmfurm** [sysoppl/Cities-Skylines-heightmap-generator#6]
Yes, I've got another issue 🙄 

Whenever i export to PNG from Photoshop, it saves as a perfectly white PNG. I don't know why this is happening. Any help would be appreciated (:  

![image](https://user-images.githubusercontent.com/86154178/123083595-8ac5c600-d463-11eb-8730-9e6a6fdc27bc.png)

**Comment by sysoppl** [comment]
I'm using PL version, but you need to change Image>Mode>Gray or similar (as in picture) and then export

![obraz](https://user-images.githubusercontent.com/30871217/123442220-f4191680-d5d4-11eb-8395-cefcfdf19db8.png)
