### ISSUE TITLE
Height Maps too extreme for City Skylines

### ISSUE THREAD

**Issue by GhostKid3904** [sysoppl/Cities-Skylines-heightmap-generator#65]
I am making a heightmap of Flagstaff, Arizona, which for some reason when imported into City Skylines looks atrocious and without any actual map details recognizable to the area, save for the airport's flat area. Could this be an issue with how the elevation change of the area is or is this a limit of City Skylines.

With some further testing on Page, Arizona, it seems as if the contours the heightmap is finding is going from 0 to max for each contour area, making this repeating pattern of 0 to max for each contour section. Additionally, the area that is a lake actually shows as the highest section and completely flat. Am I using this program wrong?
![Flagstaff 1](https://user-images.githubusercontent.com/110196714/181616537-893d9d89-b5a4-4f2e-8f94-a2b6ab0a4070.png)
?
![Page 1](https://user-images.githubusercontent.com/110196714/181618713-80acdcf2-dfa0-4384-b25d-c1ca763b75de.png)

**Comment by sysoppl** [comment]
I'm not developing this software anymore, just hosting it. I will however merge any pull requests, so please create one if you can. 
Thanks
