### ISSUE TITLE
Heightmap is not producing

### ISSUE THREAD

**Issue by Taco2077** [sysoppl/Cities-Skylines-heightmap-generator#67]
Heightmaps are not producing when I click on the buttons (both .raw and .png). Rarely works but I'd click on the produce map button then the heightmap button. But recently that seems to not work anymore

**Comment by sysoppl** [comment]
Clear cache, cookies, try different browser. It's working for me without any problems on two computers

**Comment by Taco2077** [comment]
okie

**Comment by Taco2077** [comment]
yeah, the cache/cookies might be the problem

**Comment by Taco2077** [comment]
ok, that fixed the issue. Sorry about that, I guess I wasn't thinking.
