### ISSUE TITLE
Software development announcement

### ISSUE THREAD

**Issue by sysoppl** [sysoppl/Cities-Skylines-heightmap-generator#73]
Hello.

As a lot of you probably saw, I'm not developing this software anymore. I'm just hosting it as it is.
Due to lot of work I'm not able to keep it up to date and fix anything.
This service is using mapbox as tile provider. It is a paid service, and this software is open source. Free mapbox tokens are used in about 3-5 days, so it is impossible to host it for a longer time, as it requires generating new tokens (which in long term probably is not legal anyway). We have tried to set up custom tile server, but I don't have the skills (I'm not using this much JS) to replace mapbox with custom one (see https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/21)

HOWEVER
If you have the skills you can always create PR and I will merge it and update site. 

Stay safe

**Comment by delebash** [comment]
Very nice job on this.  I made an app like this before I found yours.  I like how you do the tile selection.  I did not even realize you where doing multi tile select until I looked at the code.  You are def a much better coder than me and understand the math. I just kinda hacked and slashed.  I am thinking about redoing my app and maybe start fresh from a fork of yours.  Here is my app if you want to take a look https://terrain.justgeektechs.com/#/ source code is herer , it's a little sloppy https://github.com/delebash/unreal_mapbox_bridge  I also solved the token problem, I just make the users create a free mapbox account.  I just added maptiler as mapbox now requires credit card info for their free accounts.  When I do the rewrite I think I will use mablibre.  Again awesome job.  Cheers!
