### ISSUE TITLE
Long and Lat coordinates

### ISSUE THREAD

**Issue by maggo72** [sysoppl/Cities-Skylines-heightmap-generator#77]
Today you get one pair of coordinates for Long and Lat, however if you want to extract map image from openstreetmap for example, using export function you need to enter two pairs of Long and Lat coordinates. Is it possible to get that kind of information to be outputted into the txt file when you download the heightmap? It would be nice if this kind of data was available. This is not a issue, but I did not know where to put in this "request/improvement" (sorry).

**Comment by maggo72** [comment]
Saw that you can download other layers for example, satellite and streets..etc. this may solve my problem,

**Comment by delebash** [comment]
If you download the zip version it has a text file with this info
