### ISSUE TITLE
Website loads as nothing but gray

### ISSUE THREAD

**Issue by ArchiveDinner** [sysoppl/Cities-Skylines-heightmap-generator#82]
![heightmap generator](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/139093586/4773d599-e85f-4e9a-a9e3-ca10fa9372d6)
This issue occurs in both versions of the site (Beta and Regular), unsure of why this occurred as the first time I visited the site everything worked fine and every other use since has had this issue.

**Comment by sysoppl** [comment]
Right click > inspect > console and show any errors. Also try to delete cache, as the website works for me from different networks and devices. Do you have any adblockers?

**Comment by FATTYTRACER** [comment]
i have the same problem, i ahev tried removing add block i tried using vpn, i tried using incognito, i tried clearing cache but nothing works. im gonna attach a pic with the inspect console errors. please if you have any solution, do tell me what to do
![image11](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/165123025/f48c0510-41c6-4bc6-be77-bac540aad528)

**Comment by sysoppl** [comment]
Mapbox token expired. Its a paid service, so this tool uses free tier which has limited resources. There is an idea to use own token, but not released yet

**Comment by sysoppl** [comment]
fixed
