### ISSUE TITLE
Can't Open Website

### ISSUE THREAD

**Issue by gavinwrivera** [sysoppl/Cities-Skylines-heightmap-generator#85]
I can't open the website anymore. It just shows a blank map and the search bar doesn't appear. Is this due to too many API requests?

**Comment by sysoppl** [comment]
Well the page works for me. Delete cache / web data. Open dev tools and show console output, check network also.

![image](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/30871217/84027eea-0847-4dc0-9419-80d9eee6e628)

If there are too many api requests the downloaded map will be black, not the page.

**Comment by gavinwrivera** [comment]
It seems to have worked. Thank you!
