### ISSUE TITLE
map size issue

### ISSUE THREAD

**Issue by matiziol** [sysoppl/Cities-Skylines-heightmap-generator#9]
Downloaded heightmap is ~74% the size of what I marked on the website, when lined up with a screengrab from the website it looks like this (pic) for both png and raw. 
![heightmapoverlayed](https://user-images.githubusercontent.com/86927247/124395262-5ecbff80-dd03-11eb-813f-b3c93881849c.png)
Other than that, it works great, thanks for creating it!!!

**Comment by sysoppl** [comment]
Duplicate, please see https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/3
This is **probably** related to https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/3#issuecomment-868970358 

> If the image is perfectly aligned at the equator, it will be magnified in the north on same settings
