### ISSUE TITLE
Expired api key => white screen

### ISSUE THREAD

**Issue by llx001** [sysoppl/Cities-Skylines-heightmap-generator#90]
Hello,
It looks your API token is no longer valid for MapBox.
The result is no map data and a white screen.

This is the js error:
Object { status: 401, url: "https://api.mapbox.com/styles/v1/mapbox/outdoors-v11?access_token= {{APIKEY}}", name: "e", message: "Unauthorized: you may have provided an invalid Mapbox access token. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes", stack: "" }
evented.js:140:20

I have censored the api key i am not sure if its public or not.

**Comment by gilberdn90** [comment]
Where do you add the new Access token? I'm new to all this. and thanks

**Comment by sysoppl** [comment]
Sorry to hear, mapbox is paid service, and there was about 10000 users monthly visiting this generator. I was thinking about changing it or self hosting in https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/21 but this project for me is dead, so any PRs are welcome. If you want to use it, clone it and change API key here: https://github.com/sysoppl/Cities-Skylines-heightmap-generator/blob/5ac2306fe45243ecec927d209b6c1dee7e553492/src/app.js#L47 then you need to self host it.

**Comment by gilberdn90** [comment]
Ok, because I have an Access token. And thank you for replying. When you say host, do you mean to run it?

**Comment by gilberdn90** [comment]
Where do we support?

**Comment by sysoppl** [comment]
Hmm. Yeah, I like the idea of users getting own mapbox token and pasting it to the app. I might add this

**Comment by gilberdn90** [comment]
Takes the pressure off you!

**Comment by OceanHotelVibes** [comment]
> Sorry to hear, mapbox is paid service, and there was about 10000 users monthly visiting this generator. I was thinking about changing it or self hosting in #21 but this project for me is dead, so any PRs are welcome. If you want to use it, clone it and change API key here:
> 
> https://github.com/sysoppl/Cities-Skylines-heightmap-generator/blob/5ac2306fe45243ecec927d209b6c1dee7e553492/src/app.js#L47
> 
> then you need to self host it.

use this key for now: pk.eyJ1IjoiYmVydGRldm4iLCJhIjoiY2t2dXF1ZGhyMHlteTJ2bzJjZzE3M24xOCJ9.J5skknTRyh-6RoDWD4kw2w

**Comment by ifangc** [comment]
How should I fix this？How to clone it and change API key？and thanks

**Comment by falcon4ever** [comment]
FWIW:

- You'll need to update the mapbox gl key (create a mapbox account and generate a new token)
- You will also need to replace the fontawesome key or the icons wont render in the side panel (again create a free account and replace the hash in the index.html).

**Comment by sysoppl** [comment]
fixed:
- now you need to put own mapbox api token to make this app work
- replaced fa icons with tabler icons
- bumped some libs

I tested this quickly and looks like everything is working and I'm able to download maps. If any issues occur please open new issue.
