### ISSUE TITLE
As of 2-APR-2024, blank screen and unable to download any data or see the map.

### ISSUE THREAD

**Issue by jefrezicus67** [sysoppl/Cities-Skylines-heightmap-generator#93]
The side bar menus pop out, but no map data is being displayed:
![image](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/122387070/b4d09c69-8c35-4078-9a85-208d1bd6bd8b)

**Comment by Conjurethedead** [comment]
me too :(

**Comment by HILIOL** [comment]
可能是节日的问题，外网进不去

**Comment by sysoppl** [comment]
see https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/90

**Comment by 123ysys** [comment]
> 可能是节日的问题，外网进不去

不是，你看看海外的人也进不去。这是因为站长的api token 用完了

**Comment by ifangc** [comment]
> > 可能是节日的问题，外网进不去
> 
> 不是，你看看海外的人也进不去。这是因为站长的API token 用完了
如何解决这个问题？

**Comment by 123ysys** [comment]
> > > 可能是节日的问题，外网进不去
> > 
> > 
> > 不是，你看看海外的人也进不去。这是因为站长的API token 用完了
> > 如何解决这个问题？

没什么办法，我这几天也在尝试。一种是想办法去mapbox注册个号拿个API token，然后把站长的网站克隆到自己的服务器上，但我用过这种方法后发现这种方案下载下来的raw是有问题的，参见[issue 95](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/95)。另一个想法是把API提供给作者，但作者似乎不管这个项目了，我开issue也没人理，感觉没有什么合理的方法。
