### ISSUE TITLE
No Functionality 

### ISSUE THREAD

**Issue by mrzbornak** [sysoppl/Cities-Skylines-heightmap-generator#94]
I've been checking the site for 48 hours now and all that loads is the option bar on the left side of the screen and a blank space where the map should be on the page (see screenshot). 

If the site is no longer supported, can someone please just let us know so we can find a replacement? Seems like none of the issues opened have been addressed in 12+ months. Just a quick "move on" will suffice. :) 

![HMIssue](https://github.com/sysoppl/Cities-Skylines-heightmap-generator/assets/165968000/4217eabf-04a0-48b1-af6a-df6d6bed70c1)

**Comment by sysoppl** [comment]
see https://github.com/sysoppl/Cities-Skylines-heightmap-generator/issues/90
