### ISSUE TITLE
Downloaded RAW from self hosted server seems like has some problems, and the RAW file seems can not supported by some image editor

### ISSUE THREAD

**Issue by 123ysys** [sysoppl/Cities-Skylines-heightmap-generator#95]
Hello. I self hosted the website on my own server and use my own mapbox tokens but seems like have some problems when using RAW. I imported it into some game engines and the raised height area of the tile appears as several parallel straight lines, instead of rising like the real height data. Why does this happen? Thank you.

**Comment by 123ysys** [comment]
Also, I noticed that maybe the raw file has some incorrect such as they can not be recognized by ufraw. And it will show nothing after opened by RawTherapee.

**Comment by lpinter** [comment]
Can you provide instructions on how to self-host the site on a Windows 11 workstation?

**Comment by lpinter** [comment]
Thank you, 123ysys. I have documented the self-hosting process at https://pinter.org/archives/15848

**Comment by sysoppl** [comment]
fixed:
- now you need to put own mapbox api token to make this app work
- replaced fa icons with tabler icons
- bumped some libs

I tested this quickly and looks like everything is working and I'm able to download maps. If any issues occur please open new issue.
