### ISSUE TITLE
Please provide instructions for self-hosting

### ISSUE THREAD

**Issue by lpinter** [sysoppl/Cities-Skylines-heightmap-generator#97]
I would like to self-host your awesome site and use it with my own MapBox token to reduce the load on your token.
Please provide instructions on how to self host your site, I have a Windows 11 workstation. 

As others suggested, if the site would have a field for a token, everyone could create and use their own MapBox token, so you would not have to maintain and pay for it.

Thank you so much for the great service you provide for the community.

**Comment by Justang-14** [comment]
I have had success with my own token, kind of. I just replaced the token in the code and ran the whole the in the console, which loads the map, but the downloads still won't work for some reason.

**Comment by n3gpCTS** [comment]
> I have had success with my own token, kind of. I just replaced the token in the code and ran the whole the in the console, which loads the map, but the downloads still won't work for some reason.

I've had the same issue when I tried this method. Any solution so far?

**Comment by Justang-14** [comment]
I found a fork of this called Unreal Map Bridge, for height map imports etc. to Unreal studio. It still has the same web functionality. map.justgeektechs.com

**Comment by sysoppl** [comment]
1. Clone repo
2. Create nginx / apache server and configure it (google: digitalocean apache2 lamp, but ignore mysql and php part)
3. Upload files to the server
4. Change api token in app.js
5. Enjoy
