### ISSUE TITLE
Cities: Skylines Not working

### ISSUE THREAD

**Issue by AlettaSmith** [sysoppl/Cities-Skylines-heightmap-generator#98]
Thank you for letting my report that I visited your site Cities: Skylines https://heightmap.skydark.pl/# to create a hight map for unreal Engine, but there is no map visible and the settings does not respond. Will this issue continue for a while, because I saw online that many people have this issue.

Thank you 
Aletta Smith
scriptsales101@gmail.com

**Comment by lpinter** [comment]
You can host the map generator on your workstation. I have documented the process at https://pinter.org/archives/15848

**Comment by sysoppl** [comment]
fixed:
- now you need to put own mapbox api token to make this app work
- replaced fa icons with tabler icons
- bumped some libs

I tested this quickly and looks like everything is working and I'm able to download maps. If any issues occur please open new issue.
