### ISSUE TITLE
Uploading/Using the heightmaps in the map editor

### ISSUE THREAD

**Issue by gabrielvelasquez** [sysoppl/Cities-Skylines-heightmap-generator#99]
Thank you for making this program. I had some success before with creating maps in the map editor of Cities Skylines, but now I forgot where to place the hightmap and map image. I haven't been able to remember or to find how to upload the map into the map editor.

**Comment by gabrielvelasquez** [comment]
I kept searching and I found it, so here it is for anyone else who comes looking here.
C:\Users\YOURUSERNAME\AppData\Local\ColossalOrder\Cities_Skylines\Addons\MapEditor\Heightmaps

**Comment by sysoppl** [comment]
Its not related to this app, Im sure you figured it out already
